# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-11 09:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='inbox',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inbox',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2017, 7, 11, 9, 16, 13, 266520, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='inbox',
            name='mimetype',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='inbox',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inbox',
            name='processed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inbox',
            name='sender',
            field=models.CharField(default='', max_length=30),
        ),
    ]
