# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-11 09:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170711_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=255)),
                ('mimetype', models.CharField(default='', max_length=20)),
                ('receiver', models.CharField(default='', max_length=30)),
                ('body', models.TextField(default='')),
                ('chat_found', models.IntegerField(default=0, max_length=1)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(default=datetime.datetime(2017, 7, 11, 9, 26, 20, 929986, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='inbox',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2017, 7, 11, 9, 26, 20, 929171, tzinfo=utc)),
        ),
    ]
