# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-13 14:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170711_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2017, 7, 13, 14, 50, 5, 858263, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2017, 7, 13, 14, 50, 5, 859229, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='processed',
            field=models.IntegerField(default=0),
        ),
    ]
