# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-15 07:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170713_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2017, 8, 15, 7, 16, 40, 288436, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2017, 8, 15, 7, 16, 40, 288884, tzinfo=utc)),
        ),
    ]
